name: TATX Auto Push
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  push_data:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch and Push
        run: |
          # ดึงข้อมูล
          DATA=$(curl -sL "https://tinfoil.ultranx.ru/tinfoil/index.json")
          # ส่งไปที่โดเมนหลัก (เพื่อเลี่ยงปัญหา DNS ของ Subdomain)
          curl -X POST "http://neozteon.site/update.php" \
            --data-urlencode "key=TATX_SECRET_2026" \
            --data-urlencode "target=ultra" \
            --data-urlencode "json_data=$DATA"
